# Generated by Django 5.2.8 on 2025-11-26 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_falla', models.TextField()),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('diagnostico', 'En Diagnóstico'), ('reparacion', 'En Reparación'), ('finalizado', 'Reparado'), ('entregado', 'Entregado')], default='ingresado', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField()),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('trabajando', 'Trabajando'), ('espera_repuesto', 'Esperando Repuesto'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado')], default='pendiente', max_length=30)),
                ('notificado', models.BooleanField(default=False)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.dispositivo')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestosUsados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.reparacion')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.repuesto')),
            ],
        ),
    ]
